### ISSUE TITLE
How to make an authorised mutation?

### ISSUE THREAD

**Issue by jkhaui** [psyphore/graphql-net_core-neo4j#2]
This is really amazing, the only resource I can find integrating a .NET + GraphQL + Neo4j stack.

I'm trying a sample mutation in the playground:

```
mutation {
  createPerson(person: {id: "323r23r"}) {
		id
  }
}
```

Which returns the error message `"The current user is not authorized to access this resource.",` - how might I overcome this?

**Comment by psyphore** [comment]
hello, apologies for the delay.

you will want to add the Authorization header on your mutation request like this:
 ![image](https://user-images.githubusercontent.com/4490427/98369371-81f1c280-2041-11eb-8628-cdb8269e4e8c.png)

then on your middleware, you can validate that the jwt is valid and has the correct permissions.
I hope I've understood your question and have answered it.

**Comment by jkhaui** [comment]
Hey, thanks for the suggestion

Unfortunately though I don't even get the `CreateUser` mutation appear - any ideas?

![image](https://user-images.githubusercontent.com/36477474/98491358-ad1a2300-2288-11eb-97e9-4ad6c5fa4953.png)

**Comment by psyphore** [comment]
Hello, so the example I was building here was for Auth0 (other any other Identity Service Provider) to issue a JWT.

Therefore, the createPerson that you see here is just an auto-generated Mutation based on the models that I have exposed thanks to HotChocolate package.

Another path you can take is to expose a signin mutation that is hooked up to a service that will generate JWTs and store them locally.

**Comment by jkhaui** [comment]
Awesome - thanks for the explanation @psyphore 

I come from a Node.js background so these GraphQL libraries for .NET are all new to me. But it'd be great to see a C# implementation of the GRANDstack (https://github.com/grand-stack/grand-stack-starter) eventually. Hopefully I can learn enough to contribute, yours seems like the only viable equivalent at the moment
